### ISSUE TITLE
Failed Render Error

### ISSUE THREAD

**Issue by clbemre** [fjcaetano/ReCaptcha#116] opened 2022-02-23 07:23 UTC
Hello, I've been looking for the source of the problem for 2 days but I can't find it. Why is it throwing such an error?
## Logs
Recaptha encountered an error in execution

## Additional context

<img width="367" alt="image" src="https://user-images.githubusercontent.com/7671284/155276259-40856d79-8aa1-49b2-9aa4-dda134a98c33.png">

**Comment by fjcaetano** [comment] 2022-02-23 14:11
There's virtually no information here to be able to infer anything that may be affecting you. Please, try to stick to the issue template because it was designed to help you provide as much information as possible. I'll close this issue, but please reopen it using the provided issue template

**Closed as completed by fjcaetano** 2022-02-23 14:11 UTC
Labels: missing-template

**Comment by clbemre** [comment] 2022-03-01 07:40
Hello again. @fjcaetano 
There is no other information I can provide you, when I debug, I see that the source of the problem is faileRender, but there is no information about the cause or exception.

**maybe you can tell me what might be causing the failedRender error.**

all i see in the log are constraints errors.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/7671284/156125682-ca7f04cc-7e20-4864-8a2f-8de168247767.png">

**Comment by clbemre** [comment] 2022-03-02 15:48
Hey i'm sorry but it's very important problem for me, could you help me please? I could not solve this problem.
(I have used the same way in another project and it works but it doesn't work my current project.)
Xcode 13
IOS min target 13

thank you. @fjcaetano

**Comment by fjcaetano** [comment] 2022-03-02 15:56
@clbemre It looks like the height of the webview or view you're using to display the ReCaptcha has height zero. The view you pass to the `validate` method needs to be visible and have a valid frame with width and height greater than zero, otherwise the JS engine isn't properly started.

My suggestion for troubleshooting and checking if you can get the error to stop is setting a fixed frame on the webview. Then, if that works, you can look for a more permanent solution.

**Comment by clbemre** [comment] 2022-03-03 11:17
![image](https://user-images.githubusercontent.com/7671284/156554131-06b5a6d8-2739-4ce9-bcd1-f757e7222999.png)

@fjcaetano 
I solved the constraints issues with a temporary code. However, that is not the problem, recaptcha does not appear on the screen in any way. I checked correctly in my APIKey. It is really interesting.
