### ISSUE TITLE
WKErrorDomain Code=4

### ISSUE THREAD

**Issue by andrewcookies** [fjcaetano/ReCaptcha#44] opened 2018-07-18 15:26 UTC
Hi,
I created a simple project, identical to your Example, in which I only setup recaptcha and call the validate function. The UI is made by an empty UIView
I have created API keys and My APIdomain is "localhost", XCode 9.4.
When I start the application the log which appears is : 
[JS LOG]: did load
[JS LOG]: executing
[JS LOG]: resetting
[JS LOG]: executing
[JS LOG]: resetting
[JS LOG]: executing
[JS LOG]: resetting
[JS LOG]: executing
[JS LOG]: resetting
[JS LOG]: executing
[JS LOG]: resetting
[JS LOG]: executing
[JS LOG]: resetting
......

and the error is: 

"Unexpected Error: Error Domain=WKErrorDomain Code=4 \"A JavaScript exception occurred\" UserInfo={NSLocalizedDescription=A JavaScript exception occurred}"

Is it a problem of the backend configuration? In this case how can I simulate the flow only from app side?

Thanks for the support

**Comment by fjcaetano** [comment] 2018-07-18 17:19
Hi @AndreaGrantu, some things that may be worth for you to check:

1 - Have you registered `localhost` as a valid domain when you created your ReCaptcha key?
2 - Have you tried prepending `http://` or `https://` to localhost?
3 - If not, is the lib throwing a warning in the console that you should do so?

If none of those work, could you provide access to an example project where these may be happening?

**Comment by andrewcookies** [comment] 2018-07-19 08:37
Hi,
1 - Yes
2 - In my Info.plist I inserted either http:// than https://, but the app
has always the same behavior
3 - There's no lib warning raised

here's my project and also a screenshot of the Google settings page.

Thanks for the support

Andrea

2018-07-18 19:19 GMT+02:00 Flávio Caetano <notifications@github.com>:

**Comment by fjcaetano** [comment] 2018-07-19 14:43
This seems to be a duplicate of #7. I'm closing this issue for now, but feel free to reopen it if the fix doesn't work for you.

**Closed as completed by fjcaetano** 2018-07-19 14:43 UTC
Labels: duplicate, waiting-reply
