### ISSUE TITLE
How to Stop executing or resetting??

### ISSUE THREAD

**Issue by hinaHingrajia** [fjcaetano/ReCaptcha#122] opened 2022-08-18 11:09 UTC
I'm using the v2 reCaptcha for invisible 

its continuing logging

[JS LOG]: executing
[JS LOG]: resetting

how to stop this behaviour?
Cause its causing crash to application.

**Comment by Voxsie** [comment] 2022-09-14 07:26
Did you found a way to solve this problem?

**Comment by hinaHingrajia** [comment] 2022-09-14 07:32
Nope not yet

**Comment by fjcaetano** [comment] 2022-09-20 15:05
There's not a lot of information on this issue to investigate anything. You haven't provided any logs or useful information that could help diagnose the issue. This issue is not even following the bug reporting template which was designed to help provide as much information as possible to help troubleshoot.

I'm closing this issue, because there's nothing that can be done here, however feel free to reopen it if you're willing to provide more data that can help figure out what's going on.

**Closed as completed by fjcaetano** 2022-09-20 15:05 UTC
Labels: missing-template

**Comment by Voxsie** [comment] 2022-09-23 08:47
Hello @fjcaetano! That's what he writes to me in the console. There is a very heavy load on the device resources and these messages are constantly generated. Reset and stop functions are not working
![image](https://user-images.githubusercontent.com/72042693/191924102-075ed469-fcf9-4a93-997e-6d38ef749e93.png)
