### ISSUE TITLE
Doesn't work for me as expected

### ISSUE THREAD

**Issue by DeewaSharma** [fjcaetano/ReCaptcha#93] opened 2020-07-27 08:03 UTC
Captcha comes sometimes only all the other time it just validate user without opening captcha. Call did finished loading -> event next and then  Event completed -> isDisposed.
The appearance is random I am not getting any error or warnings it simply opens sometimes and everything works fine and other times it does not.

Testing on iPhone 11 Pro simulator.

**Comment by fjcaetano** [comment] 2020-07-28 19:17
@DeewaSharma I'm not sure I understood what the issue is. Please, try to follow the issue template since it was designed to help you provide the most detailed information possible.

I'll close this issue, but please, reopen it with the proper template.

**Closed as completed by fjcaetano** 2020-07-28 19:17 UTC
Labels: missing-template

**Comment by DeewaSharma** [comment] 2020-07-30 05:59
@fjcaetano Thank you so much for getting back to me, seems like the issue was related to simulator on real device captcha appears just fine.
Will get back to you after testing on various other devices.
