### ISSUE TITLE
Intermittent Error

### ISSUE THREAD

**Issue by JulioBBL** [fjcaetano/ReCaptcha#70] opened 2019-03-26 20:42 UTC
I get two different outcomes, seemingly at random, at times all go as planned, but other times i get the error `Unexpected Error: Error Domain=WKErrorDomain Code=4 "Ocorreu uma exceção JavaScript" UserInfo={WKJavaScriptExceptionLineNumber=24, WKJavaScriptExceptionMessage=TypeError: Argument 1 ('target') to MutationObserver.observe must be an instance of Node, WKJavaScriptExceptionColumnNumber=13, WKJavaScriptExceptionSourceURL=http://com.btg.pactual.digital.mobile/, NSLocalizedDescription=Ocorreu uma exceção JavaScript}`

tested on iPhone 6 and 6S, both on iOS 12.1.4, using the latest pod version

**Comment by fjcaetano** [comment] 2019-03-27 21:28
Hey @JulioBBL, this seems like it may be an error with the [embedded HTML](https://github.com/fjcaetano/ReCaptcha/blob/master/ReCaptcha/Assets/recaptcha.html#L38).

Do you have any way of reproducing it?

**Comment by JulioBBL** [comment] 2019-03-27 21:53
If i create the ReCaptcha object, setup the we view configuration callback and validate all in rapid succession, I get this error.

Upon further testing i figured if there is a delay before validating, no error is produced, so i made a *executive decision* to force a 2 seconds delay between calls

(Gambiarra e tal)

I can only assume there is a delay somewhere handled by another thread.

**Comment by fjcaetano** [comment] 2019-03-28 14:20
Are you using `localhost` as the domain, by any chance?

Btw, I'll close this because it seems to be a duplicate of #69.

**Closed as completed by fjcaetano** 2019-03-28 14:20 UTC
Labels: duplicate

**Comment by JulioBBL** [comment] 2019-03-28 14:27
nope, using my own domain.

**Comment by JulioBBL** [comment] 2019-03-28 16:03
i am sorry, i just now realised that i have provided you the wrong error message, this is the one i get:

`ERROR: TypeError: undefined is not an object (evaluating 'document.getElementsByTagName("div")[4].outerHTML = ""')`

only found out when you marked it as duplicate

**Comment by fjcaetano** [comment] 2019-04-04 17:38
@JulioBBL are you by any chance using ReCaptcha v3? That seems to be causing many issues with this library.

If that's your case, please try using a **v2 Invisible** key. I'll look into adding support for v3 keys soon
