### ISSUE TITLE
Intermittent WTF::HashTable Bug

### ISSUE THREAD

**Issue by MalcolmScoffable** [fjcaetano/ReCaptcha#77] opened 2019-07-08 08:57 UTC
## Bug description
We've noticed the following intermittent crash for a small number of our users since starting to use the ReCaptcha library in our app:
<img width="1244" alt="Screenshot 2019-07-08 at 09 51 38" src="https://user-images.githubusercontent.com/24914554/60797033-74cf7580-a166-11e9-9f7c-4c2186936c8c.png">

We haven't been able to reproduce this on either our own devices or simulators, however it still appears on a consistent basis. It doesn't affect everyone, but we do get a couple of reports a week (via Firebase Crashlytics). It appears to be related to the use of WebKit, but other than that we are not sure what is causing this or how to fix it, other than that it appears to be related to this library.

Has anyone else come across this, and found a way to fix or avoid? We're pretty stumped as to what's going on.

**Comment by fjcaetano** [comment] 2019-07-15 19:31
That does seem to be a bug related to WebKit. I honestly have no idea of what could be going on there since I've never seen that error before. Let me know if you find any way to reproduce it and in what types of device that is happening.

Meanwhile, I'd advice you to keep an eye in [WebKit](https://github.com/WebKit/webkit) and their [Bugzilla](https://bugs.webkit.org/query.cgi?format=specific&product=WebKit).

I'm closing this for now since it seems to be unrelated to this library, but rather an issue with WebKit. Feel free to reach out and reopen this issue if you want to.

**Closed as completed by fjcaetano** 2019-07-15 19:31 UTC
