### ISSUE TITLE
How to position Recaptcha V2 challenge popup in the center of the viewport?

### ISSUE THREAD

**Issue by Qiubeijun** [fjcaetano/ReCaptcha#125] opened 2023-03-22 13:21 UTC
When challenge popup is displayed for the first time, it is displayed on the left side of the page, but when click the confirm button and the verification fails, it is displayed in the middle again. Is there any way to make it always display in the middle?
![IMG_0271](https://user-images.githubusercontent.com/30207227/226917408-2529c7f3-9b5b-4949-a485-cf4f0bfc94ab.PNG)
![IMG_0272](https://user-images.githubusercontent.com/30207227/226917419-e2a7a647-5162-4648-855d-2c69eae27528.PNG)

**Comment by fjcaetano** [comment] 2023-03-23 17:58
This looks like a duplicate of #38 

Can you take a look if that solves it for you?

**Closed as completed** 2023-09-18 20:24 UTC
Labels: duplicate
