### ISSUE TITLE
How to print errors

### ISSUE THREAD

**Issue by yildirimatcioglu** [fjcaetano/ReCaptcha#89] opened 2020-05-30 13:28 UTC
When using with example projects site key and domainURL its working but in our site key and domainURL its not working. How can I get to errors? There is no error on console.

**Comment by fjcaetano** [comment] 2020-05-30 22:30
Errors are thrown upon initialization and in `validate`'s callback.

It looks like your issue might be a duplicate of #7 and #35. I'd also suggest you to thoroughly read the [full documentation](http://blog.flaviocaetano.com/ReCaptcha/) since it explains how to acquire keys and setup the library

I'm closing this for now, but feel free to reopen it if you think it's unrelated to those issues.

**Closed as completed by fjcaetano** 2020-05-30 22:30 UTC
